name: Build and test tmplr
on:
  - push
  - pull_request

jobs:
  build-test-install:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-15]
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        run: make CC=${{ matrix.cc }}
      - name: Test
        run: make test
      - name: Install
        run: make install PREFIX=target
      - name: Check installation
        run: |
          test -f target/bin/tmplr
          test -f target/share/man/man1/tmplr.1
          test -f target/include/tmplr.h
